version: '3.8'

services:
  webapi:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: webapi
    ports:
      - "5000:80"
    volumes:
      - ./WebApi:/app
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ContactsManagementDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
